"""Initial migration

Revision ID: 976a8fc536b8
Revises: 
Create Date: 2026-07-27 22:36:43.171148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976a8fc536b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('equipment_needed', sa.Boolean(), nullable=True),
    sa.CheckConstraint("category IN ('Strength', 'Cardio', 'Flexibility', 'Balance')", name='check_category_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('duration_minutes > 0', name='check_duration_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds > 0', name='check_duration_positive'),
    sa.CheckConstraint('reps IS NOT NULL OR duration_seconds IS NOT NULL', name='check_reps_or_duration'),
    sa.CheckConstraint('reps IS NULL OR reps > 0', name='check_reps_positive'),
    sa.CheckConstraint('sets IS NULL OR sets > 0', name='check_sets_positive'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_id', 'exercise_id', name='unique_workout_exercise')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_exercises')
    op.drop_table('workouts')
    op.drop_table('exercises')
    # ### end Alembic commands ###
